spring.application.name=book-service

# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8082

logging.level.org.apache.catalina=DEBUG
logging.level.org.springframework.web=DEBUG
spring.web.error.include-exception=true
spring.web.error.include-stacktrace=always

services.genre-service.url=http://genre-service-app:8081

spring.security.oauth2.client.registration.genre-service.client-id=book-service
spring.security.oauth2.client.registration.genre-service.client-secret=bn4KscKHYEgSdaw2dzYMC7lxM7hZrcsi
spring.security.oauth2.client.registration.genre-service.authorization-grant-type=client_credentials

spring.security.oauth2.client.provider.genre-service.token-uri=http://keycloak:8080/realms/spring-microservices-security-realm/protocol/openid-connect/token

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-security-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/spring-microservices-security-realm/protocol/openid-connect/certs
