spring.application.name=user-service

server.port=8083

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3309/user_service
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update

jwt.secret=9vX7s2mP4qW8zK1jL5hN3bV6cC0xZ9rY8tU1iO4pQ7wE3rT2yU5iI8oO1pP3aA5sS
jwt.header=Authorization

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

app.security.admin-emails=admin_admin@mail.com,admin@company.com,superuser@company.com,ceo@company.com

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-security-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/spring-microservices-security-realm/protocol/openid-connect/certs