spring.application.name=user-service

server.port=8083

jwt.secret=9vX7s2mP4qW8zK1jL5hN3bV6cC0xZ9rY8tU1iO4pQ7wE3rT2yU5iI8oO1pP3aA5sS
jwt.header=Authorization

spring.kafka.bootstrap-servers=localhost:9092

app.security.admin-emails=admin_admin@mail.com,admin@company.com,superuser@company.com,ceo@company.com