services:
  user-db:
    image: mysql:latest
    container_name: mysql-us
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: user_service
    ports:
      - "3309:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
