services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres_db
    ports:
      - "5433:5432"
    networks:
      - shared-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d postgres_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:10-alpine
    container_name: flyway
    networks:
      - shared-network
    depends_on:
      - db
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    command: -url=jdbc:postgresql://db:5432/postgres_db -user=root -password=root migrate

  book-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-service-app
    ports:
      - "8082:8082"
    networks:
      - shared-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - spring.datasource.hikari.connection-timeout=45000
      - spring.datasource.hikari.initialization-fail-timeout=45000
      - GENRE_SERVICE_URL=http://genre-service-app:8081
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://identity-provider:8181/realms/spring-microservices-security-realm
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/spring-microservices-security-realm/protocol/openid-connect/certs

volumes:
  postgres_data:

networks:
  shared-network:
    external: true
    name: library-app-network

